hyperledger/firefly-evmconnect

go.mod, go.sum
See https://github.com/hyperledger/firefly-signer/pull/20
=> Latest ffsigner and fftm

go.mod, go.sum
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
=> Update firefly-signer to v0.9.18

go.mod, go.sum, internal/ethereum/event_listener.go, internal/ethereum/event_listener_test.go, internal/msgs/en_error_messges.go
Depends on https://github.com/hyperledger/firefly-transaction-manager/pull/32 for EthConnect compatibility, where these options were combined.
> Currently this PR pulls in a commit from FFTM until there's a release with PR 32 in it
=> Allow requesting of looking up the signer, separate from an array of methods

internal/ethereum/blocklistener.go, internal/ethereum/get_block_info.go
Instead of swallowing `ErrorNotFound` for `blockRPCMethods`, surface it for consumers to decide how to handle the error. Also updated the evmconnect blocklistener implementation to not exit the loop on this error.
=> surface `ErrorNotFound` in get_block_info

internal/ethereum/event_stream.go, internal/ethereum/event_stream_test.go
Noticed cruft like this in the logs, due to an unnecessary call:
```
[2022-08-30T15:42:10.936Z] ERROR evmconnect: RPC[000001286] <-- ERROR: FF22012: Backend RPC request failed eventstream=0182ef67-007c-7d84-206d-eb3364392daf
[2022-08-30T15:42:10.936Z]  WARN evmconnect: Error uninstalling filter '': FF22012: Backend RPC request failed eventstream=0182ef67-007c-7d84-206d-eb3364392daf
```
=> Do not uninstall empty filters

go.mod, go.sum
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
=> Update to firefly-signer v0.9.19

internal/ethereum/event_stream.go
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
=> Add contract address to filter for catchup

.gitignore, cmd/config.go, cmd/config_docs_generate_test.go, cmd/config_docs_test.go, config.md, go.mod, go.sum, internal/ethereum/error_mapping.go, internal/ethereum/statuses.go, internal/ethereum/statuses_test.go
Signed-off-by: hfuss <haydenfuss@gmail.com>
=> GET /status/* APIs for Liveness and Readiness Probes

internal/ethereum/event_listener.go, internal/ethereum/event_stream.go, internal/ethereum/event_stream_test.go
Fixes https://github.com/hyperledger/firefly-evmconnect/issues/23
Explanation in extra log statement in test
=> Fix TestCatchupThenRejoinLeadGroup intermittent failure

go.mod, go.sum, internal/ethereum/send_transaction.go, internal/ethereum/send_transaction_test.go
Consumes the flag added in https://github.com/hyperledger/firefly-transaction-manager/pull/40
Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>
=> add support for raw transactions

go.mod, go.sum
Signed-off-by: Jim Zhang <jim.zhang@kaleido.io>
=> Update dependency fftm version to 1.1.5

go.mod, go.sum
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
=> Upgrade to FFTM v1.2.2

go.mod, go.sum, internal/ethereum/get_receipt.go, internal/ethereum/get_receipt_test.go
This is the evmconnect portion of https://github.com/hyperledger/firefly-transaction-manager/pull/61 to take advantage of the new field
=> Add contractLocation to receipts

internal/ethereum/event_listener.go, internal/ethereum/event_listener_test.go, internal/ethereum/event_stream.go, internal/ethereum/event_stream_test.go
=> Treat enrichment failures due to JSON/RPC errors as errors, not partial success

internal/ethereum/event_stream.go
Realized this is needed in addition to #57 to fix #53
=> Reset filter after enrichment failure

README.md
Readme update to spell out the eth Methods required for this specific EVM connector implementation
=> update readme to list all eth methods

internal/ethereum/error_mapping.go, internal/ethereum/estimate_gas.go, internal/ethereum/exec_query.go, internal/ethereum/exec_query_test.go, internal/msgs/en_error_messages.go
=> Wrap all "execution reverted" calls with error code FF23021

config.md, evmconnect_config.yml, go.mod, go.sum, internal/ethereum/send_transaction.go
pick up https://github.com/hyperledger/firefly-transaction-manager/pull/74
=> pick up transaction manager with config fix

Makefile, config.md, internal/ethereum/config.go, internal/ethereum/ethereum.go, internal/ethereum/ethereum_test.go, internal/ethereum/event_listener_test.go, internal/ethereum/get_receipt.go, internal/msgs/en_config_descriptions.go, internal/msgs/en_error_messages.go
- also removes unused TTL config option
closes #70
=> add LRU cache for transaction info

internal/ethereum/get_receipt.go, internal/ethereum/get_receipt_test.go
Add `errorMessage` field to the receipt when a transaction fails by calling `debug_traceTransaction`.  Given that this is not certain to be implemented on all clients, we tolerate any errors and just omit the errorMessage from the receipt .
This has been tested on besu and quorum with a `require` statement in the contract causing the revert.  As yet I have been unable to prove that this is also effective in the case where there is not enough gas.  So not claiming that this fixes https://github.com/hyperledger/firefly-evmconnect/issues/60 just yet but it is a useful fix nonetheless.
=> Error receipt

go.mod, go.sum
=> pick fftm 1.2.14 with fix for mtls in fftm client

config.md, internal/ethereum/config.go, internal/ethereum/error_mapping.go, internal/ethereum/ethereum.go, internal/ethereum/send_transaction_test.go, internal/msgs/en_config_descriptions.go
As per title.
- Adding a new pattern matching for known transactions
- Expose the maxConcurrentRequests option introduced by https://github.com/hyperledger/firefly-signer/pull/36 for connector level request concurrency control
=> Error matching and throttling fix

go.mod, go.sum
Picks up https://github.com/hyperledger/firefly-transaction-manager/releases/tag/v1.3.2
=> pick up transaction manager v1.3.2

go.mod, go.sum
picks up https://github.com/hyperledger/firefly-transaction-manager/pull/98
=> pick up fftm 1.3.3
